name = "tripcrafti"
pages_build_output_dir = "dist"

[vars]
PUBLIC_SUPABASE_URL = "https://cyusoliinkrsrtxgtbbl.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5dXNvbGlpbmtyc3J0eGd0YmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTEzNDAsImV4cCI6MjA3NDcyNzM0MH0.rQUT-Em7pzomm0l4JDZbGWcsYk6vfZUL3Xs2NJfmXuM"
PUBLIC_FX_API_BASE = "https://api.exchangerate.host"
DEBUG_LOGGING = "false"

[secrets]
UNSPLASH_ACCESS_KEY
GEMINI_API_KEY
EXCHANGERATE_API_KEY
